### ISSUE TITLE
Skeletons shoot inconsistently and never drop even when chance is set to 100.0

### ISSUE THREAD

**Issue by ghost** [2008Choco/AlchemicalArrows#9]
Tested with Spigot 1.14.4 and Bukkit 1.14.3 with just this plugin and default configurations.

All arrows work perfectly when shot by players but skeletons themselves will only seldom shoot explosive arrows (by default this should be disabled) and after killing a significant amount of skeletons There was not a single drop of Alchemical arrows.

The same effect was observed when the rates where ramped up to 100.0

**Comment by 2008Choco** [comment]
This would be because I'm silly. It seems I've put the wrong condition. If you were to set arrows to _not_ be shootable by skeletons, they will be shootable. I'll correct this in a future version, though for the time being, setting that arrows _should not_ be shootable by skeletons _will_ be shootable by skeletons

**Comment by GAGG1111111** [comment]
Yes that'll do it, recently tested and it's as such Skeletons that shoot the opposite. the drop system is still buggy but all the other features work perfectly.
